# Generated by Django 5.2.8 on 2025-11-28 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_publication', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descripción breve')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_title')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_favorite')],
            },
        ),
    ]
