# Generated by Django 5.2.8 on 2025-11-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_of_publication',
            new_name='publication_date',
        ),
    ]
