# Generated by Django 5.2.8 on 2025-11-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_year_of_publication_book_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
